//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.05 at 12:33:48 PM CEST 
//


package rs.dzoks.dokumenti.model;

import com.google.gson.annotations.Expose;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="documents" type="{http://dzoks.rs/service/soap}documentsListSOAP"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public class DocumentsResponse {

    @Expose
    protected DocumentsListSOAP documents;
    @Expose
    protected String error;

    public String getError() {
        return error;
    }

    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the documents property.
     *
     * @return possible object is
     * {@link DocumentsListSOAP }
     */
    public DocumentsListSOAP getDocuments() {
        return documents;
    }


    /**
     * Sets the value of the documents property.
     *
     * @param value allowed object is
     *              {@link DocumentsListSOAP }
     */
    public void setDocuments(DocumentsListSOAP value) {
        this.documents = value;
    }

}
